
# variables for hosts with docker directly on bare os - vm/metal

# general environment

var_files:
- ../ansible-local-vars.yml

# todo
# if you use a proxy, add all docker hosts to no_proxy as a comma separated list, e.g.
# no_proxy: <ip1>,<ip2>
no_proxy:


# settings for docker configuration

# parameters for ufw rules for docker communication

# todo (mandatory)
# add source networks that should access internal docker ports here, e.g.
# docker_src:
# - <network-ip>/<bits>
# - <host-ip>/32

docker_src:

# todo
# add source networks that should access published docker ports here or leave this setting to use the same as docker_src:

docker_service_src: "{{ docker_src }}"

# todo
# adjust the ports on which public services are made available

docker_service_ports:
- 80
- 8080:8099

# todo (mandatory)
# add a map of hosts and their public IP addresses here
# public_ip_map:
#   <hostname1>: <ip1>
#   <hostname2>: <ip2>

public_ip_map:

# todo
# add a map of swarm parameters here, e.g.
# swarm_config:
#  <host1>:
#    manager: true
#  <host2>:
#    manager: true
#    join: <host1>
#  <host3>:
#    join: <host1>
# which gives a swarm of host1 as first manager, host2 as manager that joins host1 and host3 that joins the swarm as worker.
# for dedicated managers add dedicated: true to the managers.

swarm_config:

# todo
# add configuration of some docker containers, e.g.
#docker_containers:
#  <host1>: [
#    { name: c01, parameters: "-p 8080:8080", image: descom/iac-webapp },
#    { name: c02, parameters: "-p 8081:8080", image: descom/iac-webapp }
#  ]
# parameters:
# name (mandatory): the name of the container
# parameters (optional): parameters passed 1:1 to docker run
# image (mandatory): the image from which the container is created
# see also ansible/roles/spinup/tasks/containers.yml

docker_containers:

# todo
# add configuration of some swarm services, e.g.
#swarm_services:
#  dcch0021: [
#    { name: s01, parameters: "-p 8082:8080", image: descom/iac-webapp },
#    { name: s02, replicas: 4, parameters: "-p 8082:8080", image: descom/iac-webapp }
#  ]
# parameters:
# name (mandatory): the name of the container
# replicas (optional): number of replicas
# parameters (optional): parameters passed 1:1 to docker service create
# image (mandatory): the image from which the service is created
# see also ansible/roles/spinup/tasks/services.yml

swarm_services:
