# tasks to install docker from upstream package
# see https://store.docker.com/editions/community/docker-ce-server-ubuntu
---
- name: update apt cache
  apt:
    update_cache: yes

- name: install apt-transport-https, ca-certificates, curl, software-properties-common
  apt:
    name: "{{ item.name }}"
  with_items:
  - { name: "apt-transport-https" }
  - { name: "ca-certificates" }
  - { name: "curl" }
  - { name: "software-properties-common" }

- name: add gpg key for docker repo
  shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"
  args:
    warn: no

- name: add docker repo
#  command: "add-apt-repository \"deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable\""
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    update_cache: yes
    state: present

- name: install latest docker-ce package
  apt:
    name: docker-ce
    state: latest
