# playbook to set up lxd remotes on management host(s)
---
- hosts: management-hosts
  vars_files:
  - ../ansible-vault
  remote_user: "{{ management_user }}"
  become: yes
  become_method: sudo
  roles:
  - vars
  - lxd-client
